data:
    # name: 'retina_train'
    dataset: 'retina_train' # 'coco'

    labels: datasets/retina_train/label # datasets/magicpoint_synth20_homoAdapt100_coco_f1/predictions
    vessel: datasets/retina_train/vessel
    root: # datasets/COCO
    root_split_txt: # /datasets/COCO

    gaussian_label:
        enable: true
        params:
            GaussianBlur: {sigma: 0.2}


    cache_in_memory: false
    preprocessing:
        resize: [1024, 1024]
        # resize: [480, 640], [240, 320], [384, 512], [1024, 1024]
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: false  # not implemented
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true # true
        valid_border_margin: 3

front_end_model: 'Train_model_heatmap'  # 'Train_model_frontend'

training:
    workers_train: 4 # 16
    workers_val: 2 # 2

model:
    # name: 'magic_point'
    # name: 'SuperPointNet_heatmap'
    name: 'SuperPointNet_resnet' # SuperPointNet_gauss2, SuperPointNet
    params: {
    }
    detector_loss:
        loss_type: 'softmax'


    batch_size: 8 # 8, 16, 32
    eval_batch_size: 4 # 8, 16, 32
    learning_rate: 0.00001 # 0.000001
    detection_threshold: 0.015 # 0.015
    lambda_loss: 0.1 # 1
    lambda_vessel_loss: 100 # 1
    topk: 10    # 5, 10, 15
    nms: 4
    dense_loss:
        enable: false
        params:
            descriptor_dist: 4 # 4, 7.5
            lambda_d: 800 # 800
    sparse_loss:
        enable: true
        params:
            num_matching_attempts: 1000
            num_masked_non_matches_per_match: 100
            lamda_d: 1
            dist: 'cos'
            method: '2d'
    other_settings: 'train 2d, gauss 0.2'
    # subpixel:
        # enable: false
        # params:
        #     subpixel_channel: 2
        # settings: 'predict flow directly'
        # loss_func: 'subpixel_loss_no_argmax' # subpixel_loss, subpixel_loss_no_argmax

retrain: True # set true for new model
reset_iter: True # set true to set the iteration number to 0
train_iter: 1000000 # 170000, 200000
validation_interval: 2000 # 200, 2000
tensorboard_interval: 20 # 200
save_interval: 10000 # 200, 2000
validation_size: 5
max_epoch: 150
n_epoch: 1  # interval for checkpoint/validation

# pretrained: 'pretrained/superpoint_v1.pth'
# pretrained: 'logs/superpoint_coco_heat2_0/checkpoints/superPointNet_170000_checkpoint.pth.tar'
# pretrained: 'logs/superpoint_retina_test_from_scratch/checkpoints/superPointNet_80_checkpoint.pth.tar'
# pretrained: 'logs/superpoint_retina_1024_train_detector_from_pretrained/checkpoints/superPointNet_10_checkpoint.pth.tar'
# pretrained: 'logs/superpoint_retina_1024_train_detector_from_pretrained_v1/checkpoints/superPointNet_6_checkpoint.pth.tar'
# pretrained: 'logs/superpoint_retina_triplet/checkpoints/superPointNet_20_checkpoint.pth.tar'
# pretrained: 'logs/superpoint_retina_top10/checkpoints/superPointNet_90_checkpoint.pth.tar'
# pretrained: 'logs/superpoint_retina/checkpoints/superPointNet_50_checkpoint.pth.tar'



